services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    networks:
      - my-network

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL=PLAINTEXT
      - KAFKA_LISTENER_NAME=PLAINTEXT
      - KAFKA_LISTENER_PORT=9092
      - KAFKA_LISTENER_HOST_NAME=kafka
      - KAFKA_ADVERTISED_LISTENER_NAME=PLAINTEXT
      - KAFKA_ADVERTISED_LISTENER_PORT=9092
      - KAFKA_LISTENER_NAMES=PLAINTEXT
      - KAFKA_LISTENER_INTERFACE=0.0.0.0
    depends_on:
      - zookeeper
    networks:
      - my-network

  producer:
    build: ./producer
    depends_on:
      - kafka
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
